### ISSUE TITLE
Error After Installation

### ISSUE THREAD

**Issue by trueman61** [batiste/django-page-cms#186]
Hi, 
I get this error after installation. I'd appreciate it if you could help me.

```
System check identified 2 issues (0 silenced).
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "c:\users\warwin\appdata\local\programs\python\python38-32\Lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\users\warwin\appdata\local\programs\python\python38-32\Lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\deneme\venv\lib\site-packages\django\utils\autoreload.py", line 54, in wrapper
    fn(*args, **kwargs)
  File "c:\deneme\venv\lib\site-packages\django\core\management\commands\runserver.py", line 120, in inner_run
    self.check_migrations()
  File "c:\deneme\venv\lib\site-packages\django\core\management\base.py", line 453, in check_migrations
    executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
  File "c:\deneme\venv\lib\site-packages\django\db\migrations\executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "c:\deneme\venv\lib\site-packages\django\db\migrations\loader.py", line 49, in __init__
    self.build_graph()
  File "c:\deneme\venv\lib\site-packages\django\db\migrations\loader.py", line 274, in build_graph
    raise exc
  File "c:\deneme\venv\lib\site-packages\django\db\migrations\loader.py", line 248, in build_graph
    self.graph.validate_consistency()
  File "c:\deneme\venv\lib\site-packages\django\db\migrations\graph.py", line 195, in validate_consistency
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "c:\deneme\venv\lib\site-packages\django\db\migrations\graph.py", line 195, in <listcomp>
    [n.raise_error() for n in self.node_map.values() if isinstance(n, DummyNode)]
  File "c:\deneme\venv\lib\site-packages\django\db\migrations\graph.py", line 58, in raise_error
    raise NodeNotFoundError(self.error_message, self.key, origin=self.origin)
django.db.migrations.exceptions.NodeNotFoundError: Migration pages.0002_page_sites dependencies reference nonexistent parent node ('sites', '0001_initial')
```

**Comment by trueman61** [comment]
I forgot to add it. Problem solved.

```
PAGE_USE_SITE_ID = True
SITE_ID = 1
```
